# -*- coding: utf-8 -*-
"""streamlite.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VSTAV0eM6QAe5G7D7f06bnLOoxFSc70K
"""

import streamlit as st

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

import plotly.express as px

link='https://raw.githubusercontent.com/murpi/wilddata/master/quests/cars.csv'

voiture=pd.read_csv(link,sep=',')
voiture

voiture.info()

voiture=voiture.sort_values('year',ascending=True)
voiture

voiture['year']=voiture['year'].astype(str)
voiture.info()

st.title('Bienvenue sur mon application! enjoy it!')

st.write("j'espère que je saurais utiliser streamlite pour de bon!")

fig_corr=sns.heatmap(voiture.corr(),center=0,cmap = sns.color_palette("vlag", as_cmap=True),annot=True)
st.pyplot(fig_corr)

st.__version__

fig1=px.bar(voiture,x="continent",y="cylinders",animation_frame="year",title="les 10 pays avec un nombre d'homicide elevé")
fig1.show()







